export const dashboardHtml = String.raw`<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="dark">
  <title>BCL Bridge Control</title>
  <style>
    :root{--bg:#090b11;--panel:#121620;--panel2:#181d29;--line:#292f3d;--text:#f6f7fb;--muted:#9aa3b4;--brand:#8b5cf6;--brand2:#6d45dc;--ok:#34d399;--warn:#fbbf24;--danger:#fb7185;--ease:cubic-bezier(.2,.8,.2,1)}
    *{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 50% -20%,#282047 0,transparent 42%),var(--bg);color:var(--text);font-family:Inter,"Yu Gothic UI","Noto Sans JP",system-ui,sans-serif}
    button,select,input{font:inherit}.shell{width:min(1040px,calc(100% - 32px));margin:0 auto;padding:36px 0 72px}.topbar{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:28px}.brand{display:flex;align-items:center;gap:14px}.logo{display:grid;place-items:center;width:46px;height:46px;border-radius:14px;background:linear-gradient(145deg,#a78bfa,#6d45dc);box-shadow:0 12px 34px #6d45dc55;font-size:23px}.brand h1{font-size:20px;line-height:1.2;margin:0}.brand p{font-size:13px;color:var(--muted);margin:4px 0 0}.pill{display:flex;align-items:center;gap:8px;border:1px solid var(--line);background:#11151dcc;border-radius:999px;padding:8px 12px;font-size:13px;color:var(--muted)}.dot{width:8px;height:8px;border-radius:50%;background:var(--warn);box-shadow:0 0 0 4px #fbbf2420}.dot.ok{background:var(--ok);box-shadow:0 0 0 4px #34d39920}
    .grid{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:20px}.card{border:1px solid var(--line);background:linear-gradient(180deg,#151a25ee,#10141dee);border-radius:20px;box-shadow:0 18px 55px #0005;overflow:hidden}.card-head{padding:22px 24px;border-bottom:1px solid var(--line)}.card-head h2{font-size:16px;margin:0}.card-head p{font-size:13px;color:var(--muted);margin:7px 0 0}.content{padding:24px}.field{display:grid;gap:8px;margin-bottom:18px}.field label{font-size:12px;font-weight:700;color:#cbd1dd}.select,input[type=text]{width:100%;height:44px;padding:0 13px;color:var(--text);background:#0d1119;border:1px solid var(--line);border-radius:11px;outline:none;transition:border-color 160ms var(--ease),box-shadow 160ms var(--ease)}.select:focus,input[type=text]:focus{border-color:#8b5cf6;box-shadow:0 0 0 3px #8b5cf626}.select:disabled,input:disabled{opacity:.55}.row{display:grid;grid-template-columns:1fr 1fr;gap:14px}
    .members{display:grid;gap:10px;margin-top:4px}.member{display:grid;grid-template-columns:auto 1fr minmax(150px,190px);align-items:center;gap:12px;padding:12px;border:1px solid var(--line);background:var(--panel2);border-radius:14px;transition:border-color 180ms var(--ease),background 180ms var(--ease),opacity 180ms var(--ease)}.member.off{opacity:.52;background:#10141c}.toggle{position:relative;width:38px;height:22px}.toggle input{position:absolute;opacity:0}.toggle span{position:absolute;inset:0;border-radius:99px;background:#343a49;transition:background 180ms var(--ease)}.toggle span:after{content:"";position:absolute;width:16px;height:16px;left:3px;top:3px;border-radius:50%;background:white;transition:transform 180ms var(--ease)}.toggle input:checked+span{background:var(--brand)}.toggle input:checked+span:after{transform:translateX(16px)}.person{display:flex;align-items:center;gap:10px;min-width:0}.avatar{width:34px;height:34px;border-radius:50%;background:#2a3040;object-fit:cover}.person strong{display:block;font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.person small{display:block;color:var(--muted);font-size:11px;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.color-select{height:38px}.empty{text-align:center;padding:34px 16px;color:var(--muted);border:1px dashed var(--line);border-radius:14px;font-size:13px;line-height:1.8}
    .side{padding:20px}.metric{display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:16px}.metric strong{font-size:31px;letter-spacing:-1px}.metric span{font-size:12px;color:var(--muted);padding-bottom:5px}.capacity{height:8px;border-radius:99px;background:#090c12;overflow:hidden;margin-bottom:18px}.capacity i{display:block;height:100%;width:0;background:linear-gradient(90deg,#6d45dc,#a78bfa);border-radius:inherit;transition:width 220ms var(--ease)}.note{font-size:12px;line-height:1.7;color:var(--muted);margin:0 0 18px}.action{width:100%;min-height:46px;border:0;border-radius:12px;color:white;background:linear-gradient(180deg,#956cf8,#7447e8);font-weight:800;cursor:pointer;box-shadow:0 10px 22px #6d45dc35;transition:transform 120ms var(--ease),filter 160ms var(--ease),opacity 160ms var(--ease)}.action:active{transform:scale(.97)}.action:disabled{cursor:not-allowed;opacity:.38;box-shadow:none}.action.danger{background:#2a151b;color:#ff9aac;border:1px solid #642837;box-shadow:none}.reason{min-height:34px;margin:10px 2px 0;color:var(--muted);font-size:11px;line-height:1.5}.reason.error{color:#ff9aac}.status-list{display:grid;gap:9px;margin:16px 0}.status-item .recolor{height:30px;width:92px;padding:0 6px;font-size:12px;margin-left:auto}.status-item{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:11px 12px;border-radius:11px;background:#0d1119;border:1px solid var(--line);font-size:12px}.status-item b{font-size:12px}.status-item em{font-style:normal;color:var(--muted);font-size:11px}.toast{position:fixed;left:50%;bottom:24px;transform:translate(-50%,18px);opacity:0;pointer-events:none;padding:12px 16px;background:#1b2130;border:1px solid #3b4355;border-radius:12px;box-shadow:0 14px 40px #0008;font-size:13px;transition:opacity 180ms var(--ease),transform 180ms var(--ease);z-index:9}.toast.show{opacity:1;transform:translate(-50%,0)}.toast.bad{border-color:#713245;color:#ffadba}
    @media (hover:hover) and (pointer:fine){.action:not(:disabled):hover{filter:brightness(1.09)}.member:hover{border-color:#3a4255}}
    @media (max-width:760px){.shell{width:min(100% - 20px,1040px);padding-top:20px}.grid{grid-template-columns:1fr}.topbar{align-items:flex-start}.pill{font-size:0}.pill span:last-child{font-size:12px}.row{grid-template-columns:1fr}.member{grid-template-columns:auto 1fr}.member .color-select{grid-column:2}.card-head,.content{padding:18px}.side{padding:18px}}
    @media (prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;transition:none!important}}
  </style>
</head>
<body>
  <main class="shell">
    <header class="topbar"><div class="brand"><div class="logo">☄</div><div><h1>BCL Bridge Control</h1><p>Discordの待機VCから自動で振り分け</p></div></div><div class="pill"><i id="readyDot" class="dot"></i><span id="readyText">接続中…</span></div></header>
    <section class="grid">
      <div class="card"><div class="card-head"><h2>ゲームの準備</h2><p>同じ通話に集まった人へ、Among Usの色を割り当てます。</p></div><div class="content">
        <div class="row"><div class="field"><label for="guild">Discordサーバー</label><select id="guild" class="select"></select></div><div class="field"><label for="channel">最初に全員がいる通話</label><select id="channel" class="select"></select></div></div>
        <div class="field"><label for="code">Among Us ロビーコード</label><input id="code" type="text" maxlength="8" spellcheck="false" autocomplete="off" placeholder="例: ABCDEF"></div>
        <div class="field"><label>中継する人とゲーム内の色</label><div id="members" class="members"><div class="empty">Discordへ接続しています…</div></div></div>
      </div></div>
      <aside class="card"><div class="side"><div class="metric"><strong id="count">0 / 0</strong><span>選択 / Bot</span></div><div class="capacity"><i id="capacityBar"></i></div><p class="note">選択した人だけ専用VCへ移動します。PC版BetterCrewLinkを使う人はOFFのままでOKです。</p><div id="activeBox"></div><button id="start" class="action" disabled>振り分けて開始</button><p id="reason" class="reason">Botへ接続しています…</p></div></aside>
    </section>
  </main><div id="toast" class="toast" role="status"></div>
  <script>
  const COLORS=[['赤','#c51111'],['青','#132ed1'],['緑','#117f2d'],['ピンク','#ed54ba'],['オレンジ','#ef7d0e'],['黄','#f5f557'],['黒','#3f474e'],['白','#d6e0f0'],['紫','#6b2fbb'],['茶','#71491e'],['シアン','#38fedc'],['ライム','#50ef39'],['マルーン','#6b1b3b'],['ローズ','#ecc0d3'],['バナナ','#fffebe'],['グレー','#8394a3'],['タン','#9f9984'],['コーラル','#ec7578']];
  const $=id=>document.getElementById(id);let snapshot=null,busy=false,chosen=new Map(),lastChannel='',lastSnapshotKey='',saved={};
  const esc=value=>String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  function toast(message,bad=false){const el=$('toast');el.textContent=message;el.className='toast show'+(bad?' bad':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',3000)}
  function selectedGuild(){return snapshot?.guilds.find(g=>g.id===$('guild').value)}
  function selectedChannel(){return selectedGuild()?.voiceChannels.find(c=>c.id===$('channel').value)}
  function syncSelect(select,items,old,placeholder){select.innerHTML=items.length?items.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.label)+'</option>').join(''):'<option value="">'+placeholder+'</option>';if(items.some(x=>x.id===old))select.value=old;select.disabled=!items.length}
  function render(){if(!snapshot)return;const guildOld=$('guild').value;syncSelect($('guild'),snapshot.guilds.map(g=>({id:g.id,label:g.name})),guildOld,'サーバーが見つかりません');const guild=selectedGuild();const channelOld=$('channel').value;syncSelect($('channel'),(guild?.voiceChannels||[]).map(c=>({id:c.id,label:c.name+'（'+c.participantCount+'人）'})),channelOld,'人がいる通話がありません');if(!lastChannel&&$('channel').value)lastChannel=$('channel').value;renderMembers();renderSide();$('readyDot').className='dot'+(snapshot.ready?' ok':'');$('readyText').textContent=snapshot.ready?'Discord 接続済み':'接続待ち';}
  function renderMembers(){const channel=selectedChannel();if(!channel){$('members').innerHTML='<div class="empty">先に全員でDiscordの通話へ入ってください。<br>入室すると自動でここに表示されます。</div>';return}if(lastChannel!==channel.id){chosen.clear();lastChannel=channel.id}const existing=new Set(channel.participants.map(p=>p.id));for(const id of [...chosen.keys()])if(!existing.has(id))chosen.delete(id);channel.participants.forEach((p,i)=>{if(!chosen.has(p.id)){const s=saved[p.username];chosen.set(p.id,s?{enabled:s.enabled,color:s.color}:{enabled:true,color:i%COLORS.length})}});$('members').innerHTML=channel.participants.map(p=>{const pick=chosen.get(p.id);const avatar=p.avatarUrl?'<img class="avatar" src="'+esc(p.avatarUrl)+'" alt="">':'<div class="avatar"></div>';const options=COLORS.map((c,i)=>'<option value="'+i+'"'+(pick.color===i?' selected':'')+'>'+c[0]+'</option>').join('');return '<div class="member'+(pick.enabled?'':' off')+'" data-id="'+esc(p.id)+'"><label class="toggle" title="中継対象"><input type="checkbox" '+(pick.enabled?'checked':'')+'><span></span></label><div class="person">'+avatar+'<div><strong>'+esc(p.displayName)+'</strong><small>@'+esc(p.username)+'</small></div></div><select class="select color-select" '+(pick.enabled?'':'disabled')+'>'+options+'</select></div>'}).join('');document.querySelectorAll('.member').forEach(row=>{const id=row.dataset.id;const username=channel.participants.find(p=>p.id===id)?.username;row.querySelector('input').addEventListener('change',e=>{chosen.get(id).enabled=e.target.checked;savePick(username,chosen.get(id));renderMembers();renderSide()});row.querySelector('select').addEventListener('change',e=>{chosen.get(id).color=Number(e.target.value);savePick(username,chosen.get(id));renderSide()})})}
  function renderSide(){const guild=selectedGuild();const active=snapshot?.activeRounds.find(r=>r.guildId===guild?.id);const picks=[...chosen.values()].filter(x=>x.enabled);const cap=guild?.capacity||0;$('count').textContent=picks.length+' / '+cap;$('capacityBar').style.width=Math.min(100,cap?picks.length/cap*100:0)+'%';const duplicate=new Set(picks.map(x=>x.color)).size!==picks.length;const code=$('code').value.trim().toUpperCase();let reason='準備できました。';if(!snapshot?.ready)reason='Botへ接続しています…';else if(active)reason='ゲーム中です。終了すると全員を待機VCへ戻します。';else if(!selectedChannel())reason='人がいる待機VCを選んでください。';else if(!picks.length)reason='中継する人を1人以上ONにしてください。';else if(picks.length>cap)reason='Botが'+(picks.length-cap)+'体足りません。中継する人を減らすかBotを追加してください。';else if(duplicate)reason='色が重複しています。全員ちがう色にしてください。';else if(!/^[A-Z]{4,8}$/.test(code))reason='Among Usのロビーコードを入力してください。';$('reason').textContent=reason;$('reason').className='reason'+((picks.length>cap||duplicate)?' error':'');$('start').disabled=busy||Boolean(active)||reason!=='準備できました。';if(document.activeElement?.classList.contains('recolor'))return;const usedColors=active?active.participants.map(p=>p.colorId):[];$('activeBox').innerHTML=active?'<div class="status-list">'+active.participants.map(p=>{const dup=usedColors.filter(c=>c===p.colorId).length>1;const opts=COLORS.map((c,i)=>'<option value="'+i+'"'+(p.colorId===i?' selected':'')+'>'+c[0]+'</option>').join('');return '<div class="status-item"><b><span style="color:'+COLORS[p.colorId][1]+'">●</span> '+esc(p.displayName)+'</b><select class="select recolor" data-user="'+esc(p.userId)+'" data-username="'+esc(p.username)+'" title="色を間違えたらここで直せます">'+opts+'</select><em'+(dup?' style="color:#ff9aac"':'')+'>'+esc(dup?'色が重複':statusLabel(p.status))+'</em></div>'}).join('')+'</div><p class="note">色を間違えたら、上の選択欄で変えればその人だけ付け直します。</p><button id="stop" class="action danger">終了して元に戻す</button>':'';if(active){$('stop').onclick=stopRound;document.querySelectorAll('.recolor').forEach(sel=>sel.addEventListener('change',()=>recolor(sel.dataset.user,sel.dataset.username,Number(sel.value))))}}
  function statusLabel(s){return ({'starting':'起動中','waiting-for-mobile-host':'PC待ち','waiting-for-player-color':'色待ち','connected':'接続済み','voice-server-connecting':'接続中','disconnected':'終了'}[s]||s)}
  async function loadPicks(){try{const res=await fetch('/api/picks',{cache:'no-store'});saved=await res.json()}catch{saved={}}}
  function savePick(username,pick){if(!username)return;saved[username]={enabled:pick.enabled,color:pick.color};fetch('/api/picks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,enabled:pick.enabled,color:pick.color})}).catch(()=>{})}
  async function refresh(){try{const res=await fetch('/api/state',{cache:'no-store'});const next=await res.json(),key=JSON.stringify(next);snapshot=next;if(key!==lastSnapshotKey){lastSnapshotKey=key;render()}}catch{$('readyText').textContent='アプリ接続エラー';$('readyDot').className='dot'}}
  async function startRound(){const guild=selectedGuild(),channel=selectedChannel();if(!guild||!channel)return;busy=true;renderSide();channel.participants.forEach(p=>{if(chosen.has(p.id))savePick(p.username,chosen.get(p.id))});const assignments=channel.participants.filter(p=>chosen.get(p.id)?.enabled).map(p=>({userId:p.id,colorId:chosen.get(p.id).color,colorName:COLORS[chosen.get(p.id).color][0]}));try{const res=await fetch('/api/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({guildId:guild.id,waitingChannelId:channel.id,lobbyCode:$('code').value.trim().toUpperCase(),assignments})});const data=await res.json();if(!res.ok)throw new Error(data.error||'開始できませんでした');toast('振り分けを開始しました');await refresh()}catch(e){toast(e.message,true)}finally{busy=false;renderSide()}}
  async function recolor(userId,username,colorId){const guild=selectedGuild();if(!guild)return;try{const res=await fetch('/api/recolor',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({guildId:guild.id,userId,colorId})});const data=await res.json();if(!res.ok)throw new Error(data.error||'色を変えられませんでした');const saved0=saved[username];savePick(username,{enabled:saved0?saved0.enabled:true,color:colorId});toast('色を'+COLORS[colorId][0]+'に変えました')}catch(e){toast(e.message,true)}finally{document.activeElement?.blur();lastSnapshotKey='';await refresh()}}
  async function stopRound(){const guild=selectedGuild();if(!guild)return;busy=true;renderSide();try{const res=await fetch('/api/stop',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({guildId:guild.id})});const data=await res.json();if(!res.ok)throw new Error(data.error||'終了できませんでした');toast('全員を待機VCへ戻しました');chosen.clear();await refresh()}catch(e){toast(e.message,true)}finally{busy=false;renderSide()}}
  $('guild').addEventListener('change',()=>{lastChannel='';render()});$('channel').addEventListener('change',()=>{lastChannel='';renderMembers();renderSide()});$('code').addEventListener('input',e=>{e.target.value=e.target.value.toUpperCase().replace(/[^A-Z]/g,'');renderSide()});$('start').addEventListener('click',startRound);loadPicks().finally(()=>{refresh();setInterval(refresh,1500)});
  </script>
</body></html>`;
