export const SAMPLE_RATE = 48_000;
export const CHANNELS = 2;
export const FRAME_DURATION_MS = 20;
export const SAMPLES_PER_CHANNEL = (SAMPLE_RATE * FRAME_DURATION_MS) / 1000;
export const SAMPLES_PER_FRAME = SAMPLES_PER_CHANNEL * CHANNELS;
export const BYTES_PER_FRAME = SAMPLES_PER_FRAME * Int16Array.BYTES_PER_ELEMENT;
